Repository bounswe/bounswe2023group6, pull requests merged in 2023-05, with the labels that each got.

#155 Web application user interface
  .gitignore
  practice-app/app/__init__.py
  practice-app/app/static/assets/css/_notes/dwsync.xml
  practice-app/app/static/assets/css/font-awesome.min.css
  practice-app/app/static/assets/css/main.css
  practice-app/app/static/assets/fonts/FontAwesome.otf
  practice-app/app/static/assets/fonts/_notes/dwsync.xml
  practice-app/app/static/assets/fonts/fontawesome-webfont.eot
  practice-app/app/static/assets/fonts/fontawesome-webfont.svg
  practice-app/app/static/assets/fonts/fontawesome-webfont.ttf
  practice-app/app/static/assets/fonts/fontawesome-webfont.woff
  practice-app/app/static/assets/fonts/fontawesome-webfont.woff2
  practice-app/app/static/assets/js/_notes/dwsync.xml
  practice-app/app/static/assets/js/jquery.min.js
  practice-app/app/static/assets/js/jquery.scrolly.min.js
  practice-app/app/static/assets/js/main.js
  practice-app/app/static/assets/js/skel.min.js
  practice-app/app/static/assets/js/util.js
  practice-app/app/static/images/_notes/dwsync.xml
  practice-app/app/static/images/banner.jpg
  practice-app/app/static/images/pic01.jpg
  practice-app/app/static/images/pic02.jpg
  practice-app/app/static/images/pic03.jpg
  practice-app/app/static/images/pic04.jpg
  practice-app/app/static/images/pic05.jpg
  practice-app/app/static/images/worldtime.jpeg
  practice-app/app/templates/base.html
  practice-app/app/templates/example.html
  practice-app/app/templates/index.html
  practice-app/app/templates/worldtime.html
  practice-app/app/views.py
  practice-app/requirements.txt
Labels: type: task, status: review-needed

#161 Game Information API
  practice-app/app/game_information_api.py
  practice-app/app/static/images/steam-logo.png
  practice-app/app/templates/base.html
  practice-app/app/templates/get_game_information.html
  practice-app/app/templates/index.html
  practice-app/app/templates/show_all_games.html
  practice-app/app/templates/show_game_information.html
  practice-app/app/views.py
Labels: type: task, status: review-needed

#182 unittest and folder design
  practice-app/app/__init__.py
  practice-app/app/views.py
  practice-app/app/worldtime.py
  practice-app/requirements.txt
  practice-app/tests/__init__.py
  practice-app/tests/conftest.py
  practice-app/tests/test_worldtime.py
Labels: type: task, status: review-needed

#187 Implement the GET-POST Methods using the Dnd5 API
  practice-app/app/dnd_information_api.py
  practice-app/app/static/images/DnD-Symbol.png
  practice-app/app/templates/dnd.html
  practice-app/app/templates/index.html
  practice-app/app/views.py
Labels: status: review-needed

#184 Implement the GET-POST Methods using the Bored API
  .gitignore
  practice-app/app/bored_api.py
  practice-app/app/templates/base.html
  practice-app/app/templates/bored.html
  practice-app/app/templates/index.html
  practice-app/app/views.py
Labels: priority: high, area: milestone, status: review-needed

#199 implementing Melih/dnd-api-v2
  practice-app/app/dnd_information_api.py
  practice-app/app/static/images/DnD-Symbol.png
  practice-app/app/templates/dnd.html
  practice-app/app/templates/index.html
  practice-app/app/views.py
Labels: status: review-needed

#208 Frontend worldtime ahmetkudu
  practice-app/app/templates/worldtime.html
  practice-app/tests/test_worldtime.py
Labels: priority: medium, area: milestone

#205 Huzeyfe/unittest
  practice-app/tests/test_pokemon_api.py
Labels: priority: high, status: review-needed

#196 Implement status page
  practice-app/.env.example
  practice-app/app/static/images/warning.jpg
  practice-app/app/tcorp.py
  practice-app/app/templates/index.html
  practice-app/app/templates/status_page.html
  practice-app/app/views.py
  practice-app/tests/test_tcorp.py
Labels: priority: medium, type: task, status: inprogress, area: milestone, status: review-needed

#201 Add Unit Tests
  practice-app/app/bored_api.py
  practice-app/app/views.py
  practice-app/tests/test_bored_api.py
Labels: priority: high, area: milestone, status: review-needed

#216 Emresin/worldcountries
  practice-app/app/static/images/worldcountries.jpg
  practice-app/app/templates/index.html
  practice-app/app/templates/worldcountries.html
  practice-app/app/views.py
  practice-app/app/worldcountries.py
  practice-app/tests/test_worldcountries.py
Labels: status: review-needed

#211 added test_dnd_api
  practice-app/tests/test_dnd_api.py
Labels: priority: high, type: task, area: external, status: review-needed

#224 added find free games api
  practice-app/app/free_games_api.py
  practice-app/app/static/images/free_games_api.jpeg
  practice-app/app/templates/find_free_games.html
  practice-app/app/templates/index.html
  practice-app/app/templates/see_disliked_games.html
  practice-app/app/templates/see_liked_games.html
  practice-app/app/views.py
Labels: priority: high, status: review-needed

#229 add swagger functionality
  practice-app/app/bored_api.py
Labels: priority: high, type: task, area: milestone, status: review-needed
